### ISSUE TITLE
Unable to restart job on a WHB instance

### ISSUE THREAD

**Issue by srinathgit** [marklogic/data-movement#110]
The following tests has two threads which inserts documents to db followed by call to stopJob(). First thread completes its execution. Then the second thread starts and a call to dmManager.startJob(ihbMT) is ignored as calling add()  throws the following exception

```
Exception in thread "Thread-2" java.lang.IllegalStateException: This instance has been stopped
	at com.marklogic.datamovement.impl.WriteHostBatcherImpl.requireNotStopped(WriteHostBatcherImpl.java:344)
	at com.marklogic.datamovement.impl.WriteHostBatcherImpl.add(WriteHostBatcherImpl.java:289)
	at com.marklogic.datamovement.impl.WriteHostBatcherImpl.add(WriteHostBatcherImpl.java:275)
	at com.marklogic.datamovement.functionaltests.WriteHostBatcherTest$8MyRunnable.run(WriteHostBatcherTest.java:2044)
	at java.lang.Thread.run(Thread.java:745)
```
Test:

```
	@Test
	public void testAddMultiStopJob() throws Exception{
		
		final String query1 = "fn:count(fn:doc())";
		Assert.assertTrue(dbClient.newServerEval().xquery(query1).eval().next().getNumber().intValue() ==0);
		ihbMT =  dmManager.newWriteHostBatcher();
       	ihbMT.withBatchSize(11);
       	ihbMT.onBatchSuccess(
		        (client, batch) -> {
		        	System.out.println("Batch size "+batch.getItems().length);
		        	for(WriteEvent w:batch.getItems()){
		        		System.out.println("Success "+w.getTargetUri());
		        	}
		        })
		        .onBatchFailure(
		          (client, batch, throwable) -> {
		        	  throwable.printStackTrace();
		        		for(WriteEvent w:batch.getItems()){
		        			System.out.println("Failure "+w.getTargetUri());
		        		}
			        		
		       
		});
		
		
		   		
       	class MyRunnable implements Runnable {
       	  
       	  @Override
       	  public void run() {
       		 JobTicket  writeTicket = dmManager.startJob(ihbMT);
         		
           	  for (int j =0 ;j < 100; j++){
    				String uri ="/local/multi-"+ j+"-"+Thread.currentThread().getId();
    				System.out.println("Thread name: "+Thread.currentThread().getName()+"  URI:"+ uri);
    				ihbMT.add(uri, fileHandle);
    			}
           		ihbMT.flush();
				dmManager.stopJob(writeTicket);
		 }  
           		
       	} 
       	Thread t1,t2;
       	t1 = new Thread(new MyRunnable());
       	t2 = new Thread(new MyRunnable());
      
       	t1.start();
       	t1.join();
       	
       	System.out.println("Completed execution of Thread 1");
       	
       	t2.start();
        t2.join();
               	
       	Assert.assertEquals(200,dbClient.newServerEval().xquery(query1).eval().next().getNumber().intValue());
	}
```

**Comment by sammefford** [comment]
This is expected behavior.  After you stop a job, you can't restart it--you'll need to create a new instance.  This is aligned with DatabaseClient, InputStream, and other Java classes that are designed to be used then finalized only once.
