### ISSUE TITLE
NullPointerException in awaitCompletion

### ISSUE THREAD

**Issue by sammefford** [marklogic/data-movement#123]
I got a NPE when running the following code:

```
import com.marklogic.client.DatabaseClient;
import com.marklogic.client.DatabaseClientFactory;
import com.marklogic.client.DatabaseClientFactory.BasicAuthContext;
import com.marklogic.datamovement.DataMovementManager;
import com.marklogic.datamovement.JobTicket;
import com.marklogic.datamovement.WriteHostBatcher;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.Random;
import java.util.concurrent.atomic.AtomicInteger;
import java.util.concurrent.LinkedBlockingQueue;
import java.util.concurrent.ThreadPoolExecutor;
import java.util.concurrent.TimeUnit;

public class DM_WriteText {
  private static Logger logger = LoggerFactory.getLogger(DM_WriteText.class);
  static int numAddThreads = 40;
  static int numWhbThreads = 40;
  static int batchSize     = 200;
  static int totalDocs     = 5000000;
  static int docSize       = 2000;

  public static void main(String[] args) {

    String unique = "DM_WriteText_" + new Random().nextInt(10000);
    logger.info("unique={}", unique);
    DatabaseClient initClient = DatabaseClientFactory.newClient("engrlab-129-192.engrlab.marklogic.com", 8011,
      new BasicAuthContext("admin", "admin"));
    DataMovementManager moveMgr = DataMovementManager.newInstance().withClient(initClient);

    ThreadPoolExecutor threadPool = new ThreadPoolExecutor(numAddThreads, numAddThreads,
      1, TimeUnit.MINUTES, new LinkedBlockingQueue());
    AtomicInteger startPoint = new AtomicInteger(1);
    String docPrefix = "/" + unique + "/doc";
    StringBuilder contentsBldr = new StringBuilder();
    // make contents as big as docSize
    for ( int i=0; i < (docSize / 5); i++ ) {
      contentsBldr.append("text ");
    }
    String contents = contentsBldr.toString();

    WriteHostBatcher whb = moveMgr.newWriteHostBatcher()
      .withThreadCount(numWhbThreads)
      .withBatchSize(batchSize)
      .onBatchFailure((client, batch, throwable) -> throwable.printStackTrace());
    whb.onBatchSuccess((client, batch) -> {
      logger.debug("Batch written {}", batch.getJobBatchNumber());
      threadPool.execute(new AddDocs(whb, docPrefix, startPoint.addAndGet(batchSize), contents));
    });
    JobTicket ticket = moveMgr.startJob(whb);
    for ( int i=0; i < numAddThreads; i++ ) {
      int start = startPoint.get();
      threadPool.execute(new AddDocs(whb, docPrefix, start, contents));
      startPoint.addAndGet(batchSize);
    }
    whb.awaitCompletion();
    moveMgr.stopJob(ticket);
  }

  static class AddDocs implements Runnable {
    private WriteHostBatcher whb;
    private int startPoint;
    private String prefix;
    private String contents;

    AddDocs(WriteHostBatcher whb, String prefix, int startPoint, String contents) {
      this.whb = whb;
      this.prefix = prefix;
      this.startPoint = startPoint;
      logger.info("startPoint={}", startPoint);
      this.contents = contents;
    }

    public void run() {
      for ( int j=startPoint; j < startPoint + batchSize; j++ ) {
        whb.addAs(prefix + j + ".txt", contents);
      }
    }
  }
}
```

Here's the output until the NPE and slightly after:

```
16:05:32.439 [main] INFO  DM_WriteText - unique=DM_WriteText_991
16:05:32.471 [main] DEBUG c.m.client.DatabaseClientFactory - Creating new database client for server at engrlab-129-192.engrlab.marklogic.com:8011
16:05:32.487 [main] DEBUG c.m.client.impl.JerseyServices - Connecting to engrlab-129-192.engrlab.marklogic.com at 8011 as admin
16:05:32.734 [main] DEBUG c.m.client.impl.JerseyServices - Getting forestinfo as application/json
16:05:33.004 [main] INFO  DM_WriteText - startPoint=1
16:05:33.005 [main] INFO  DM_WriteText - startPoint=201
16:05:33.005 [main] INFO  DM_WriteText - startPoint=401
16:05:33.006 [main] INFO  DM_WriteText - startPoint=601
16:05:33.007 [main] INFO  DM_WriteText - startPoint=801
16:05:33.007 [main] INFO  DM_WriteText - startPoint=1001
16:05:33.007 [main] INFO  DM_WriteText - startPoint=1201
16:05:33.008 [pool-1-thread-1] INFO  c.m.d.impl.WriteHostBatcherImpl - Found 3 hosts with forests for "dmsdk_stress_test"
16:05:33.008 [main] INFO  DM_WriteText - startPoint=1401
16:05:33.009 [main] INFO  DM_WriteText - startPoint=1601
16:05:33.010 [main] INFO  DM_WriteText - startPoint=1801
16:05:33.010 [main] INFO  DM_WriteText - startPoint=2001
16:05:33.010 [pool-1-thread-1] INFO  c.m.d.impl.WriteHostBatcherImpl - Adding DatabaseClient on port 8011 for host "engrlab-128-167.engrlab.marklogic.com" to the rotation
16:05:33.010 [pool-1-thread-1] DEBUG c.m.client.DatabaseClientFactory - Creating new database client for server at engrlab-128-167.engrlab.marklogic.com:8011
16:05:33.010 [pool-1-thread-1] DEBUG c.m.client.impl.JerseyServices - Connecting to engrlab-128-167.engrlab.marklogic.com at 8011 as admin
16:05:33.012 [main] INFO  DM_WriteText - startPoint=2201
16:05:33.012 [main] INFO  DM_WriteText - startPoint=2401
16:05:33.013 [main] INFO  DM_WriteText - startPoint=2601
16:05:33.029 [main] INFO  DM_WriteText - startPoint=2801
16:05:33.029 [main] INFO  DM_WriteText - startPoint=3001
16:05:33.030 [main] INFO  DM_WriteText - startPoint=3201
16:05:33.031 [main] INFO  DM_WriteText - startPoint=3401
16:05:33.031 [main] INFO  DM_WriteText - startPoint=3601
16:05:33.031 [main] INFO  DM_WriteText - startPoint=3801
16:05:33.033 [main] INFO  DM_WriteText - startPoint=4001
16:05:33.037 [main] INFO  DM_WriteText - startPoint=4201
16:05:33.039 [main] INFO  DM_WriteText - startPoint=4401
16:05:33.040 [main] INFO  DM_WriteText - startPoint=4601
16:05:33.041 [main] INFO  DM_WriteText - startPoint=4801
16:05:33.041 [main] INFO  DM_WriteText - startPoint=5001
16:05:33.042 [main] INFO  DM_WriteText - startPoint=5201
16:05:33.043 [main] INFO  DM_WriteText - startPoint=5401
16:05:33.047 [main] INFO  DM_WriteText - startPoint=5601
16:05:33.047 [main] INFO  DM_WriteText - startPoint=5801
16:05:33.049 [main] INFO  DM_WriteText - startPoint=6001
16:05:33.049 [main] INFO  DM_WriteText - startPoint=6201
16:05:33.050 [main] INFO  DM_WriteText - startPoint=6401
16:05:33.051 [main] INFO  DM_WriteText - startPoint=6601
16:05:33.051 [main] INFO  DM_WriteText - startPoint=6801
16:05:33.051 [main] INFO  DM_WriteText - startPoint=7001
16:05:33.053 [main] INFO  DM_WriteText - startPoint=7201
16:05:33.053 [main] INFO  DM_WriteText - startPoint=7401
16:05:33.053 [main] INFO  DM_WriteText - startPoint=7601
16:05:33.054 [main] INFO  DM_WriteText - startPoint=7801
Exception in thread "main" java.lang.NullPointerException
        at com.marklogic.datamovement.impl.WriteHostBatcherImpl.awaitCompletion(WriteHostBatcherImpl.java:571)
        at com.marklogic.datamovement.impl.WriteHostBatcherImpl.awaitCompletion(WriteHostBatcherImpl.java:577)
        at DM_WriteText.main(DM_WriteText.java:58)
16:05:33.076 [pool-1-thread-1] INFO  c.m.d.impl.WriteHostBatcherImpl - Adding DatabaseClient on port 8011 for host "engrlab-129-192.engrlab.marklogic.com" to the rotation
16:05:33.076 [pool-1-thread-1] INFO  c.m.d.impl.WriteHostBatcherImpl - Adding DatabaseClient on port 8011 for host "engrlab-129-023.engrlab.marklogic.com" to the rotation
16:05:33.076 [pool-1-thread-1] DEBUG c.m.client.DatabaseClientFactory - Creating new database client for server at engrlab-129-023.engrlab.marklogic.com:8011
16:05:33.077 [pool-1-thread-1] DEBUG c.m.client.impl.JerseyServices - Connecting to engrlab-129-023.engrlab.marklogic.com at 8011 as admin
16:05:33.124 [pool-1-thread-1] INFO  c.m.d.impl.WriteHostBatcherImpl - threadCount=40
16:05:33.125 [pool-1-thread-1] INFO  c.m.d.impl.WriteHostBatcherImpl - batchSize=200
```

**Comment by sammefford** [comment]
I see how this could have happened in the old code-base.  The new code base is different enough that this isn't going to recur.
