### ISSUE TITLE
startJob should also initialize

### ISSUE THREAD

**Issue by sammefford** [marklogic/data-movement#126]
I should not get the following error when calling flush after startJob

```
Exception in thread "main" java.lang.IllegalStateException: This operation must be called after calling add or addAs
        at com.marklogic.datamovement.impl.WriteHostBatcherImpl.requireInitialized(WriteHostBatcherImpl.java:337)
        at com.marklogic.datamovement.impl.WriteHostBatcherImpl.flush(WriteHostBatcherImpl.java:482)
        at DM_WriteText.main(DM_WriteText.java:62)
```

**Comment by sammefford** [comment]
Fixed in https://github.com/marklogic/java-client-api/commit/210f0d05645cd34a5f6f625bd95ebf0ac17ffcec
