### ISSUE TITLE
Throwing more appropriate exceptions 

### ISSUE THREAD

**Issue by srinathgit** [marklogic/data-movement#20]
I am opening this enhancement request for scenarios where more appropriate exceptions can be thrown and will list them whenever I find them

1. Calling assign(String uri) method in ForestConfiguration when no forests are associated with the database.

```
java.lang.IllegalArgumentException: bound must be positive
	at java.util.Random.nextInt(Random.java:388)
	at com.marklogic.datamovement.impl.ForestConfigurationImpl.assign(ForestConfigurationImpl.java:41)
	at com.marklogic.datamovement.impl.WriteHostBatcherImpl.assign(WriteHostBatcherImpl.java:100)
	at com.marklogic.datamovement.impl.WriteHostBatcherImpl.add(WriteHostBatcherImpl.java:76)
	at com.marklogic.datamovement.impl.WriteHostBatcherImpl.add(WriteHostBatcherImpl.java:65)
	at com.marklogic.dmsdktest.WriteHostBatcherTest.testAdd(WriteHostBatcherTest.java:186)
```

**Comment by sammefford** [comment]
Thanks for pointing this out, Srinath.  I'm only closing this since ForestConfiguration is off the ML9 priority list for now.  So please feel free to open other similar issues as you run across exceptions that could use a better message.

**Comment by sammefford** [comment]
I'm moving this back to will-not-fix since I haven't run across anything specific with QueryHostBatcher that needs better error messages.
