### ISSUE TITLE
ImportDefinition job fails when directory path is provided for parameter -input_file_path

### ISSUE THREAD

**Issue by srinathgit** [marklogic/data-movement#22]
ImportDefinition job fails when directory path is provided for parameter -input_file_path instead of a file path. Looking into the exception below, I realized that hadoop.home.dir wasn't set. When I set "hadoop.home.dir" to MLCP_HOME (the lib directory in MLCP_HOME had all the necessary hadoop related jars)  and ran the job, it ran fine. This bug is to document that the applications using ImportDefinition /ExportDefinition should have HADOOP_HOME environment variable set to appropriate directory.

```
DEBUG: [DataMovementServices] argList =[IMPORT -input_file_type aggregates -output_collections fooo,bar,baz -uri_id @uri-id -output_quality 3 -output_directory /dir3 -output_permissions dls-user,read -input_file_path C:/MLSource/trunk/qa/mlcp/data/agg/nested2/ -aggregate_record_
element baz -host localhost -port 5275 -username admin -password admin]
DEBUG: [DataMovementServices] argList.size()=[25]
14:13:57.271 [main] DEBUG c.marklogic.contentpump.ContentPump - Command: IMPORT
14:13:57.271 [main] DEBUG c.marklogic.contentpump.ContentPump - Arguments: -input_file_type aggregates -output_collections fooo,bar,baz -uri_id @uri-id -output_quality 3 -output_directory /dir3 -output_permissions dls-user,read -input_file_path C:/MLSource/trunk/qa/mlcp/data/agg
/nested2/ -aggregate_record_element baz -host localhost -port 5275 -username admin -password admin
14:13:57.302 [main] DEBUG org.apache.hadoop.util.Shell - Failed to detect a valid hadoop home directory
java.io.IOException: HADOOP_HOME or hadoop.home.dir are not set.
        at org.apache.hadoop.util.Shell.checkHadoopHome(Shell.java:302) [dmsdk.jar:na]
        at org.apache.hadoop.util.Shell.<clinit>(Shell.java:327) [dmsdk.jar:na]
        at org.apache.hadoop.util.GenericOptionsParser.preProcessForWindows(GenericOptionsParser.java:438) [dmsdk.jar:na]
        at org.apache.hadoop.util.GenericOptionsParser.parseGeneralOptions(GenericOptionsParser.java:484) [dmsdk.jar:na]
        at org.apache.hadoop.util.GenericOptionsParser.<init>(GenericOptionsParser.java:170) [dmsdk.jar:na]
        at org.apache.hadoop.util.GenericOptionsParser.<init>(GenericOptionsParser.java:153) [dmsdk.jar:na]
        at com.marklogic.contentpump.ContentPump.runCommand(ContentPump.java:99) [dmsdk.jar:na]
        at com.marklogic.datamovement.impl.DataMovementServices.startMlcpJob(DataMovementServices.java:133) [dmsdk.jar:na]
        at com.marklogic.datamovement.impl.DataMovementServices.startJob(DataMovementServices.java:86) [dmsdk.jar:na]
        at com.marklogic.datamovement.DataMovementManager.startJob(DataMovementManager.java:51) [dmsdk.jar:na]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_74]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_74]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_74]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.8.0_74]
        at com.marklogic.dmsdktest.Dmsdktest.main(Dmsdktest.java:232) [dmsdk.jar:na]
14:13:57.318 [main] ERROR org.apache.hadoop.util.Shell - Failed to locate the winutils binary in the hadoop binary path
java.io.IOException: Could not locate executable null\bin\winutils.exe in the Hadoop binaries.
        at org.apache.hadoop.util.Shell.getQualifiedBinPath(Shell.java:355) [dmsdk.jar:na]
        at org.apache.hadoop.util.Shell.getWinUtilsPath(Shell.java:370) [dmsdk.jar:na]
        at org.apache.hadoop.util.Shell.<clinit>(Shell.java:363) [dmsdk.jar:na]
        at org.apache.hadoop.util.GenericOptionsParser.preProcessForWindows(GenericOptionsParser.java:438) [dmsdk.jar:na]
        at org.apache.hadoop.util.GenericOptionsParser.parseGeneralOptions(GenericOptionsParser.java:484) [dmsdk.jar:na]
        at org.apache.hadoop.util.GenericOptionsParser.<init>(GenericOptionsParser.java:170) [dmsdk.jar:na]
        at org.apache.hadoop.util.GenericOptionsParser.<init>(GenericOptionsParser.java:153) [dmsdk.jar:na]
        at com.marklogic.contentpump.ContentPump.runCommand(ContentPump.java:99) [dmsdk.jar:na]
        at com.marklogic.datamovement.impl.DataMovementServices.startMlcpJob(DataMovementServices.java:133) [dmsdk.jar:na]
        at com.marklogic.datamovement.impl.DataMovementServices.startJob(DataMovementServices.java:86) [dmsdk.jar:na]
        at com.marklogic.datamovement.DataMovementManager.startJob(DataMovementManager.java:51) [dmsdk.jar:na]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_74]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_74]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_74]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.8.0_74]
        at com.marklogic.dmsdktest.Dmsdktest.main(Dmsdktest.java:232) [dmsdk.jar:na]
14:13:57.520 [main] DEBUG c.marklogic.contentpump.ContentPump - Running in: localmode
14:13:57.520 [main] INFO  c.m.contentpump.LocalJobRunner - Content type: XML
14:13:57.739 [main] DEBUG o.a.h.m.lib.MutableMetricsFactory - field org.apache.hadoop.metrics2.lib.MutableRate org.apache.hadoop.security.UserGroupInformation$UgiMetrics.loginSuccess with annotation @org.apache.hadoop.metrics2.annotation.Metric(sampleName=Ops, always=false, abou
t=, type=DEFAULT, value=[Rate of successful kerberos logins and latency (milliseconds)], valueName=Time)
14:13:57.739 [main] DEBUG o.a.h.m.lib.MutableMetricsFactory - field org.apache.hadoop.metrics2.lib.MutableRate org.apache.hadoop.security.UserGroupInformation$UgiMetrics.loginFailure with annotation @org.apache.hadoop.metrics2.annotation.Metric(sampleName=Ops, always=false, abou
t=, type=DEFAULT, value=[Rate of failed kerberos logins and latency (milliseconds)], valueName=Time)
14:13:57.739 [main] DEBUG o.a.h.m.lib.MutableMetricsFactory - field org.apache.hadoop.metrics2.lib.MutableRate org.apache.hadoop.security.UserGroupInformation$UgiMetrics.getGroups with annotation @org.apache.hadoop.metrics2.annotation.Metric(sampleName=Ops, always=false, about=,
 type=DEFAULT, value=[GetGroups], valueName=Time)
14:13:57.754 [main] DEBUG o.a.h.m.impl.MetricsSystemImpl - UgiMetrics, User and group related metrics
14:13:57.832 [main] DEBUG org.apache.hadoop.security.Groups -  Creating new Groups object
14:13:57.832 [main] DEBUG o.a.hadoop.util.NativeCodeLoader - Trying to load the custom-built native-hadoop library...
14:13:57.832 [main] DEBUG o.a.hadoop.util.NativeCodeLoader - Failed to load native-hadoop with error: java.lang.UnsatisfiedLinkError: no hadoop in java.library.path
14:13:57.848 [main] WARN  o.a.hadoop.util.NativeCodeLoader - Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
14:13:57.848 [main] DEBUG o.a.hadoop.util.PerformanceAdvisory - Falling back to shell based
14:13:57.848 [main] DEBUG o.a.h.s.JniBasedUnixGroupsMappingWithFallback - Group mapping impl=org.apache.hadoop.security.ShellBasedUnixGroupsMapping
14:13:57.848 [main] DEBUG org.apache.hadoop.security.Groups - Group mapping impl=org.apache.hadoop.security.JniBasedUnixGroupsMappingWithFallback; cacheTimeout=300000; warningDeltaMs=5000
14:13:57.848 [main] DEBUG o.a.h.security.UserGroupInformation - hadoop login
14:13:57.848 [main] DEBUG o.a.h.security.UserGroupInformation - hadoop login commit
14:13:57.864 [main] DEBUG o.a.h.security.UserGroupInformation - using local user:NTUserPrincipal: xxxx
14:13:57.864 [main] DEBUG o.a.h.security.UserGroupInformation - Using user: "NTUserPrincipal: xxxx" with name xxxx
14:13:57.864 [main] DEBUG o.a.h.security.UserGroupInformation - User entry: "xxxx"
14:13:57.864 [main] DEBUG o.a.h.security.UserGroupInformation - UGI loginUser:xxxx
(auth:SIMPLE)
14:13:57.957 [main] DEBUG c.m.contentpump.LocalJobRunner - Thread pool size: 4
14:13:57.988 [main] ERROR c.marklogic.contentpump.ContentPump - Error running a ContentPump job
java.lang.NullPointerException: null
        at java.lang.ProcessBuilder.start(Unknown Source) ~[na:1.8.0_74]
        at org.apache.hadoop.util.Shell.runCommand(Shell.java:482) ~[dmsdk.jar:na]
        at org.apache.hadoop.util.Shell.run(Shell.java:455) ~[dmsdk.jar:na]
        at org.apache.hadoop.util.Shell$ShellCommandExecutor.execute(Shell.java:715) ~[dmsdk.jar:na]
        at org.apache.hadoop.util.Shell.execCommand(Shell.java:808) ~[dmsdk.jar:na]
        at org.apache.hadoop.util.Shell.execCommand(Shell.java:791) ~[dmsdk.jar:na]
        at org.apache.hadoop.fs.FileUtil.execCommand(FileUtil.java:1097) ~[dmsdk.jar:na]
        at org.apache.hadoop.fs.RawLocalFileSystem$DeprecatedRawLocalFileStatus.loadPermissionInfo(RawLocalFileSystem.java:582) ~[dmsdk.jar:na]
        at org.apache.hadoop.fs.RawLocalFileSystem$DeprecatedRawLocalFileStatus.getPermission(RawLocalFileSystem.java:557) ~[dmsdk.jar:na]
        at org.apache.hadoop.fs.LocatedFileStatus.<init>(LocatedFileStatus.java:42) ~[dmsdk.jar:na]
        at org.apache.hadoop.fs.FileSystem$4.next(FileSystem.java:1699) ~[dmsdk.jar:na]
        at org.apache.hadoop.fs.FileSystem$4.next(FileSystem.java:1681) ~[dmsdk.jar:na]
        at org.apache.hadoop.mapreduce.lib.input.FileInputFormat.singleThreadedListStatus(FileInputFormat.java:303) ~[dmsdk.jar:na]
        at org.apache.hadoop.mapreduce.lib.input.FileInputFormat.listStatus(FileInputFormat.java:264) ~[dmsdk.jar:na]
        at com.marklogic.contentpump.FileAndDirectoryInputFormat.getSplits(FileAndDirectoryInputFormat.java:75) ~[dmsdk.jar:na]
        at com.marklogic.contentpump.LocalJobRunner.run(LocalJobRunner.java:128) ~[dmsdk.jar:na]
        at com.marklogic.contentpump.ContentPump.runJobLocally(ContentPump.java:308) ~[dmsdk.jar:na]
        at com.marklogic.contentpump.ContentPump.runCommand(ContentPump.java:205) ~[dmsdk.jar:na]
        at com.marklogic.datamovement.impl.DataMovementServices.startMlcpJob(DataMovementServices.java:133) [dmsdk.jar:na]
        at com.marklogic.datamovement.impl.DataMovementServices.startJob(DataMovementServices.java:86) [dmsdk.jar:na]
        at com.marklogic.datamovement.DataMovementManager.startJob(DataMovementManager.java:51) [dmsdk.jar:na]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_74]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_74]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_74]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.8.0_74]
        at com.marklogic.dmsdktest.Dmsdktest.main(Dmsdktest.java:232) [dmsdk.jar:na]
java.lang.NullPointerException
        at java.lang.ProcessBuilder.start(Unknown Source)
        at org.apache.hadoop.util.Shell.runCommand(Shell.java:482)
        at org.apache.hadoop.util.Shell.run(Shell.java:455)
        at org.apache.hadoop.util.Shell$ShellCommandExecutor.execute(Shell.java:715)
        at org.apache.hadoop.util.Shell.execCommand(Shell.java:808)
        at org.apache.hadoop.util.Shell.execCommand(Shell.java:791)
        at org.apache.hadoop.fs.FileUtil.execCommand(FileUtil.java:1097)
        at org.apache.hadoop.fs.RawLocalFileSystem$DeprecatedRawLocalFileStatus.loadPermissionInfo(RawLocalFileSystem.java:582)
        at org.apache.hadoop.fs.RawLocalFileSystem$DeprecatedRawLocalFileStatus.getPermission(RawLocalFileSystem.java:557)
        at org.apache.hadoop.fs.LocatedFileStatus.<init>(LocatedFileStatus.java:42)
        at org.apache.hadoop.fs.FileSystem$4.next(FileSystem.java:1699)
        at org.apache.hadoop.fs.FileSystem$4.next(FileSystem.java:1681)
        at org.apache.hadoop.mapreduce.lib.input.FileInputFormat.singleThreadedListStatus(FileInputFormat.java:303)
        at org.apache.hadoop.mapreduce.lib.input.FileInputFormat.listStatus(FileInputFormat.java:264)
        at com.marklogic.contentpump.FileAndDirectoryInputFormat.getSplits(FileAndDirectoryInputFormat.java:75)
        at com.marklogic.contentpump.LocalJobRunner.run(LocalJobRunner.java:128)
        at com.marklogic.contentpump.ContentPump.runJobLocally(ContentPump.java:308)
        at com.marklogic.contentpump.ContentPump.runCommand(ContentPump.java:205)
        at com.marklogic.datamovement.impl.DataMovementServices.startMlcpJob(DataMovementServices.java:133)
        at com.marklogic.datamovement.impl.DataMovementServices.startJob(DataMovementServices.java:86)
        at com.marklogic.datamovement.DataMovementManager.startJob(DataMovementManager.java:51)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at com.marklogic.dmsdktest.Dmsdktest.main(Dmsdktest.java:232)
14:13:58.176 [Finalizer] INFO  c.m.client.impl.DatabaseClientImpl - Releasing connection
14:13:58.176 [Finalizer] DEBUG c.m.client.impl.JerseyServices - Releasing connection
14:13:58.176 [Finalizer] DEBUG o.a.h.i.c.t.ThreadSafeClientConnManager - Shutting down
```

**Comment by sammefford** [comment]
You found the answer.  I agree.  To run the mlcp wrapper classes one must first set MLCP_HOME and HADOOP_HOME to point to the mlcp directory which contains the bin folder which contains the required binaries for hadoop.
